"""Create a small, clearly synthetic Mount Taranaki GeoTIFF for Stage 3 checks."""

from pathlib import Path

import numpy as np
import rasterio
from rasterio.transform import from_origin
from rasterio.warp import transform, transform_bounds


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "fixtures" / "taranaki-stage3-synthetic.tif"
SELECTION_WGS84 = (173.895, -39.43, 174.225, -39.155)
SUMMIT_WGS84 = (174.0632, -39.2968)
CRS = "EPSG:2193"
WIDTH = 360
HEIGHT = 360
NODATA = -9999.0


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    west, south, east, north = transform_bounds("EPSG:4326", CRS, *SELECTION_WGS84, densify_pts=21)
    resolution_x = (east - west) / WIDTH
    resolution_y = (north - south) / HEIGHT
    raster_transform = from_origin(west, north, resolution_x, resolution_y)
    columns = west + (np.arange(WIDTH) + 0.5) * resolution_x
    rows = north - (np.arange(HEIGHT) + 0.5) * resolution_y
    x, y = np.meshgrid(columns, rows)
    summit_x, summit_y = transform("EPSG:4326", CRS, [SUMMIT_WGS84[0]], [SUMMIT_WGS84[1]])
    distance = np.hypot(x - summit_x[0], y - summit_y[0])

    elevation = 58.0 + 2460.0 * np.exp(-((distance / 7200.0) ** 2))
    elevation += 34.0 * np.sin((x - west) / 1800.0) * np.exp(-distance / 11500.0)
    elevation += 17.0 * np.cos((y - south) / 1300.0)
    elevation = np.clip(elevation, 36.0, 2518.0).astype("float32")
    summit_row, summit_column = np.unravel_index(int(np.argmin(distance)), distance.shape)
    elevation[summit_row, summit_column] = 2518.0

    # An explicit missing-data patch verifies that NODATA is not mistaken for a
    # very low elevation.
    missing = ((x - (east - 2400)) ** 2 + (y - (south + 2200)) ** 2) < 850 ** 2
    elevation[missing] = NODATA

    with rasterio.open(
        OUTPUT,
        "w",
        driver="GTiff",
        width=WIDTH,
        height=HEIGHT,
        count=1,
        dtype="float32",
        crs=CRS,
        transform=raster_transform,
        nodata=NODATA,
        compress="deflate",
        tiled=True,
    ) as dataset:
        dataset.write(elevation, 1)
        dataset.update_tags(
            VERTICAL_DATUM="Synthetic Stage 3 fixture — not survey data",
            SOURCE="Generated by topomapper for regression testing",
        )

    print(f"Created {OUTPUT}")


if __name__ == "__main__":
    main()
